Added Callback functiona
timum-viw/socket.io-client pull request #5
Opened 2017-04-01 15:07 UTC by zenmanenergy

Socket.io has the ability to fire an event on a client, then have that client respond back within the same request scope. It's REALLY confusing how it works, but I seem to have to gotten it working on my system. 

It does this with the use of IDs. Instead of the packet starting with 42[ it will start with 42{id}[ For example, it may be: 425[ or 429[ This callback method will emit a packet back to the server with
43{id}[ If the server emitted 425[ then the callback would be 435[

This is extremely useful with node.js code like this:

```
socketId='-P5-l_UggL0uM0yoAAAB';
io.sockets.connected[socketId].emit('getAccessPoints',{},function(accessPoints){
	console.log(accessPoints);
});
```

Then in the Arduino code, it looks like this:

```
webSocket.on("getAccessPoints", getAccessPoints);
void getAccessPoints(const char * payload, size_t length) {
  String accessPointsJson="{\"HP-Print-b1-LaserJet 200 color\":\"-51\",\"Aslan\":\"-90\",\"gibbon.net\":\"-68\"}";
  webSocket.callback(accessPointsJson.c_str());
}
```

Two things are happening here, the socket.io server is emitting the
"getAccessPoints" to the arduino board, then the arduino board is
responding BACk to the server with the variable "accessPoints"

So the server is sending something like:
425[{"getAccessPoints"}]

The arduino is responding with:
435[{"HP-Print-b1-LaserJet 200
color":"-51","Aslan":"-90","gibbon.net":"-68"}]

I'll add a full example of it in action shortly.

2017-05-10 03:28 UTC, zenmanenergy commented
What do you mean as long as the event does not contain a comma? Is there an edge case that will cause this to fail?

2017-06-05 18:16 UTC, timum-viw requested changes
Hey, sorry it took me so long. I looked at the code and I like the functionality you added.
I'm not quite happy with the id handling though. The way you coded it, the id gets overridden if a new packet arrives before the acknowledge packet was emitted.
Could you please address this issue?
Thanks for your contribution!

2017-06-05 19:50 UTC, zenmanenergy commented
I'm not sure I understand what you mean. Are you talking about the private variable "id" getting overridden?

2017-06-05 20:10 UTC, zenmanenergy commented
I think I understand that problem. I need to ponder how to solve this. Maybe if the ID is passed back to the event function, something like this in the trigger method:

if (callbackID>-1){
e->second(payload, length, callbackID);
}else{
e->second(payload, length);
}

Then default callbackID to -1 so it doesn't break existing functionality. I'll have to play around with this. If you see a simpler solution, i'm all ears.

2018-03-01 07:58 UTC, Ouwen commented
I think you'll have to change the event map such that the function takes in some context. In this case the context can just be the id string:

```
void on(const char* event, std::function<void (const char * payload, size_t length, const char * contextId)>);
```

I was just looking for this functionality and thought that this library was very well done. @zenmanenergy I see it has been a while since this PR was looked at so I might give this a go :slightly_smiling_face:

2021-01-13 20:41 UTC, closed without merging